/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-sd:src/main/java/project/repository/Repository.e.vm.java
 */
package fr.cora.mesindicateurssi.repository.more;

import fr.cora.mesindicateurssi.domain.more.MoreTypesDemo;
import fr.cora.mesindicateurssi.repository.support.CustomRepository;

/**
 * Advanced CRUD Repository for {@link MoreTypesDemo}.
 */
public interface MoreTypesDemoRepository extends CustomRepository<MoreTypesDemo, Integer> {
}