/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/web/controller/SearchForm.e.vm.java
 */
package fr.cora.mesindicateurssi.web.controller;

import static com.google.common.collect.Lists.newArrayList;

import static fr.cora.mesindicateurssi.domain.Book_.*;
import java.io.Serializable;
import java.util.List;
import fr.cora.mesindicateurssi.domain.Book;
import fr.cora.mesindicateurssi.repository.support.NullRestriction;
import fr.cora.mesindicateurssi.repository.support.Range;
import fr.cora.mesindicateurssi.repository.support.Ranges.RangeInteger;
import fr.cora.mesindicateurssi.repository.support.SearchForm;

/**
 * SearchForm for {@link BookService}
 */
public class BookSearchForm extends SearchForm<Book> implements Serializable {
    private static final long serialVersionUID = 1L;

    private Book book = new Book();
    private RangeInteger<Book> numberOfPagesRange = new RangeInteger<Book>(numberOfPages);

    /**
     * The root book for search by example.
     * Used from the view.
     */
    @Override
    public Book getForm() {
        return book;
    }

    public Book getBook() {
        return getForm();
    }

    // Ranges, used from the view.

    public RangeInteger<Book> getNumberOfPagesRange() {
        return numberOfPagesRange;
    }

    @Override
    public List<Range<Book, ?>> getRanges() {
        List<Range<Book, ?>> result = newArrayList();
        result.add(getNumberOfPagesRange());
        return result;
    }

    private NullRestriction accountNullRestriction = new NullRestriction("account");

    public NullRestriction getAccountNullRestriction() {
        return accountNullRestriction;
    }

    @Override
    public List<NullRestriction> getNullRestrictions() {
        List<NullRestriction> result = newArrayList();
        result.add(accountNullRestriction);
        return result;
    }
}