/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/web/controller/controller.e.vm.java
 */
package fr.cora.mesindicateurssi.web.controller;

import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;

import fr.cora.mesindicateurssi.domain.Category;
import fr.cora.mesindicateurssi.repository.CategoryRepository;

@Controller
@RequestMapping("/domain/category/")
public class CategoryController {

    @Autowired
    private CategoryRepository categoryRepository;

    /**
     * Performs the list action.
     */
    @RequestMapping( { "", "list" })
    public String list(@ModelAttribute CategorySearchForm categorySearchForm, Model model) {
        Page<Category> page = categoryRepository.find(categorySearchForm);
        model.addAttribute("categoriesCount", page.getTotalElements());
        model.addAttribute("categories", page.getContent());
        return "domain/category/list";
    }

    /**
     * Serves the create form.
     */
    @RequestMapping(value = "create", method = GET)
    public String create(@ModelAttribute Category category) {
        return "domain/category/create";
    }

    /**
     * Performs the create action and redirect to the show view.
     */
    @RequestMapping(value = "create", method = { POST, PUT })
    public String create(@Valid @ModelAttribute Category category, BindingResult bindingResult) {
        if (bindingResult.hasErrors()) {
            return create(category);
        }

        categoryRepository.save(category);
        return "redirect:/domain/category/show/" + category.getId();
    }

    /**
     * Serves search by example form, search by pattern form and search by named query form.
     */
    @RequestMapping(value = "*", method = GET)
    public void catchAll(@ModelAttribute CategorySearchForm categorySearchForm) {
    }

}