/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/web/controller/SearchForm.e.vm.java
 */
package fr.cora.mesindicateurssi.web.controller;

import static com.google.common.collect.Lists.newArrayList;

import java.io.Serializable;
import java.util.List;
import fr.cora.mesindicateurssi.domain.Category;
import fr.cora.mesindicateurssi.repository.support.NullRestriction;
import fr.cora.mesindicateurssi.repository.support.SearchForm;

/**
 * SearchForm for {@link CategoryService}
 */
public class CategorySearchForm extends SearchForm<Category> implements Serializable {
    private static final long serialVersionUID = 1L;

    private Category category = new Category();

    /**
     * The root category for search by example.
     * Used from the view.
     */
    @Override
    public Category getForm() {
        return category;
    }

    public Category getCategory() {
        return getForm();
    }

    @Override
    public List<NullRestriction> getNullRestrictions() {
        List<NullRestriction> result = newArrayList();
        return result;
    }
}