/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/web/controller/restController.e.vm.java
 */
package fr.cora.mesindicateurssi.web.controller;

import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;
import static com.google.common.collect.Lists.newArrayList;

import java.io.PrintWriter;
import java.util.List;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.format.support.FormattingConversionService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import fr.cora.mesindicateurssi.web.util.AutoCompleteResult;
import fr.cora.mesindicateurssi.repository.support.SearchParameters;
import fr.cora.mesindicateurssi.domain.Category;
import fr.cora.mesindicateurssi.repository.CategoryRepository;

@Controller
@RequestMapping("domain/rest/category/")
public class CategoryRestController {
    @Autowired
    public FormattingConversionService formattingConversionService;

    @Autowired
    private CategoryRepository categoryRepository;

    @RequestMapping(value = "/", method = POST)
    @ResponseBody
    public Category create(@Valid Category category) {
        categoryRepository.save(category);
        return category.copy();
    }

    @RequestMapping(value = "/", method = POST, headers = "content-type:application/json")
    @ResponseBody
    public Category jsonCreate(@Valid @RequestBody Category category) {
        categoryRepository.save(category);
        return category.copy();
    }

    @RequestMapping(value = "/", method = GET)
    @ResponseBody
    public List<Category> list(Category category, SearchParameters searchParameters) {
        Page<Category> page = categoryRepository.findWithExample(category, searchParameters.toPageRequest());
        List<Category> ret = newArrayList();
        for (Category _category : page.getContent()) {
            ret.add(_category.copy());
        }
        return ret;
    }

    @RequestMapping(value = "/{pk}", method = GET)
    @ResponseBody
    public Category get(@PathVariable("pk") Category category) {
        return category.copy();
    }

    @RequestMapping(value = "/{pk}", method = PUT)
    @ResponseBody
    public Category update(@PathVariable("pk") Category categoryToUpdate, @Valid Category category) {
        category.copyTo(categoryToUpdate);
        categoryRepository.save(categoryToUpdate);
        return categoryToUpdate.copy();
    }

    @RequestMapping(value = "/{pk}", method = DELETE)
    @ResponseBody
    public boolean delete(@PathVariable("pk") Category category) {
        categoryRepository.delete(category);
        return true;
    }

    @RequestMapping("/autocomplete")
    @ResponseBody
    public List<AutoCompleteResult> autocomplete(@RequestParam(value = "term", required = false) String searchPattern,
            SearchParameters search) {
        if (searchPattern != null && !searchPattern.isEmpty()) {
            search.setSearchPattern(searchPattern);
        }

        List<AutoCompleteResult> ret = newArrayList();
        for (Category category : categoryRepository.find(search.getSearchPattern())) {
            String objectPk = category.getId().toString();
            String objectLabel = formattingConversionService.convert(category, String.class);
            ret.add(new AutoCompleteResult(objectPk, objectLabel));
        }
        return ret;
    }

    @ExceptionHandler()
    @ResponseStatus(value = INTERNAL_SERVER_ERROR)
    public void exception(Exception e, PrintWriter out) {
        out.write(e.getMessage());
    }
}