/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/web/controller/restController.e.vm.java
 */
package fr.cora.mesindicateurssi.web.controller;

import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;
import static com.google.common.collect.Lists.newArrayList;

import java.io.PrintWriter;
import java.util.List;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.format.support.FormattingConversionService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import fr.cora.mesindicateurssi.web.util.AutoCompleteResult;
import fr.cora.mesindicateurssi.repository.support.SearchParameters;
import fr.cora.mesindicateurssi.domain.Indicator;
import fr.cora.mesindicateurssi.repository.IndicatorRepository;

@Controller
@RequestMapping("domain/rest/indicator/")
public class IndicatorRestController {
    @Autowired
    public FormattingConversionService formattingConversionService;

    @Autowired
    private IndicatorRepository indicatorRepository;

    @RequestMapping(value = "/", method = POST)
    @ResponseBody
    public Indicator create(@Valid Indicator indicator) {
        indicatorRepository.save(indicator);
        return indicator.copy();
    }

    @RequestMapping(value = "/", method = POST, headers = "content-type:application/json")
    @ResponseBody
    public Indicator jsonCreate(@Valid @RequestBody Indicator indicator) {
        indicatorRepository.save(indicator);
        return indicator.copy();
    }

    @RequestMapping(value = "/", method = GET)
    @ResponseBody
    public List<Indicator> list(Indicator indicator, SearchParameters searchParameters) {
        Page<Indicator> page = indicatorRepository.findWithExample(indicator, searchParameters.toPageRequest());
        List<Indicator> ret = newArrayList();
        for (Indicator _indicator : page.getContent()) {
            ret.add(_indicator.copy());
        }
        return ret;
    }

    @RequestMapping(value = "/{pk}", method = GET)
    @ResponseBody
    public Indicator get(@PathVariable("pk") Indicator indicator) {
        return indicator.copy();
    }

    @RequestMapping(value = "/{pk}", method = PUT)
    @ResponseBody
    public Indicator update(@PathVariable("pk") Indicator indicatorToUpdate, @Valid Indicator indicator) {
        indicator.copyTo(indicatorToUpdate);
        indicatorRepository.save(indicatorToUpdate);
        return indicatorToUpdate.copy();
    }

    @RequestMapping(value = "/{pk}", method = DELETE)
    @ResponseBody
    public boolean delete(@PathVariable("pk") Indicator indicator) {
        indicatorRepository.delete(indicator);
        return true;
    }

    @RequestMapping("/autocomplete")
    @ResponseBody
    public List<AutoCompleteResult> autocomplete(@RequestParam(value = "term", required = false) String searchPattern,
            SearchParameters search) {
        if (searchPattern != null && !searchPattern.isEmpty()) {
            search.setSearchPattern(searchPattern);
        }

        List<AutoCompleteResult> ret = newArrayList();
        for (Indicator indicator : indicatorRepository.find(search.getSearchPattern())) {
            String objectPk = indicator.getId().toString();
            String objectLabel = formattingConversionService.convert(indicator, String.class);
            ret.add(new AutoCompleteResult(objectPk, objectLabel));
        }
        return ret;
    }

    @ExceptionHandler()
    @ResponseStatus(value = INTERNAL_SERVER_ERROR)
    public void exception(Exception e, PrintWriter out) {
        out.write(e.getMessage());
    }
}