/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/web/controller/SearchForm.e.vm.java
 */
package fr.cora.mesindicateurssi.web.controller;

import static com.google.common.collect.Lists.newArrayList;

import java.io.Serializable;
import java.util.List;
import fr.cora.mesindicateurssi.domain.Indicator;
import fr.cora.mesindicateurssi.repository.support.NullRestriction;
import fr.cora.mesindicateurssi.repository.support.SearchForm;

/**
 * SearchForm for {@link IndicatorService}
 */
public class IndicatorSearchForm extends SearchForm<Indicator> implements Serializable {
    private static final long serialVersionUID = 1L;

    private Indicator indicator = new Indicator();

    /**
     * The root indicator for search by example.
     * Used from the view.
     */
    @Override
    public Indicator getForm() {
        return indicator;
    }

    public Indicator getIndicator() {
        return getForm();
    }

    private NullRestriction categoryNullRestriction = new NullRestriction("category");

    public NullRestriction getCategoryNullRestriction() {
        return categoryNullRestriction;
    }

    @Override
    public List<NullRestriction> getNullRestrictions() {
        List<NullRestriction> result = newArrayList();
        result.add(categoryNullRestriction);
        return result;
    }
}