/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/web/controller/controller.e.vm.java
 */
package fr.cora.mesindicateurssi.web.controller;

import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;

import fr.cora.mesindicateurssi.domain.Tag;
import fr.cora.mesindicateurssi.repository.TagRepository;

@Controller
@RequestMapping("/domain/tag/")
public class TagController {

    @Autowired
    private TagRepository tagRepository;

    /**
     * Performs the list action.
     */
    @RequestMapping( { "", "list" })
    public String list(@ModelAttribute TagSearchForm tagSearchForm, Model model) {
        Page<Tag> page = tagRepository.find(tagSearchForm);
        model.addAttribute("tagsCount", page.getTotalElements());
        model.addAttribute("tags", page.getContent());
        return "domain/tag/list";
    }

    /**
     * Serves the create form.
     */
    @RequestMapping(value = "create", method = GET)
    public String create(@ModelAttribute Tag tag) {
        return "domain/tag/create";
    }

    /**
     * Performs the create action and redirect to the show view.
     */
    @RequestMapping(value = "create", method = { POST, PUT })
    public String create(@Valid @ModelAttribute Tag tag, BindingResult bindingResult) {
        if (bindingResult.hasErrors()) {
            return create(tag);
        }

        tagRepository.save(tag);
        return "redirect:/domain/tag/show/" + tag.getId();
    }

    /**
     * Serves search by example form, search by pattern form and search by named query form.
     */
    @RequestMapping(value = "*", method = GET)
    public void catchAll(@ModelAttribute TagSearchForm tagSearchForm) {
    }

}