/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/web/controller/SearchForm.e.vm.java
 */
package fr.cora.mesindicateurssi.web.controller;

import static com.google.common.collect.Lists.newArrayList;

import java.io.Serializable;
import java.util.List;
import fr.cora.mesindicateurssi.domain.Tag;
import fr.cora.mesindicateurssi.repository.support.NullRestriction;
import fr.cora.mesindicateurssi.repository.support.SearchForm;

/**
 * SearchForm for {@link TagService}
 */
public class TagSearchForm extends SearchForm<Tag> implements Serializable {
    private static final long serialVersionUID = 1L;

    private Tag tag = new Tag();

    /**
     * The root tag for search by example.
     * Used from the view.
     */
    @Override
    public Tag getForm() {
        return tag;
    }

    public Tag getTag() {
        return getForm();
    }

    @Override
    public List<NullRestriction> getNullRestrictions() {
        List<NullRestriction> result = newArrayList();
        return result;
    }
}