<%--
 | (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3-sd:src/main/webapp/WEB-INF/views/domain/ajax.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><fmt:message key="tag" />: <fmt:message key="crud.autocomplete" /></title>
</head>
<body>
	<h2><fmt:message key="tag" />: <fmt:message key="crud.autocomplete" /></h2>
	<div class="span-6">
		<input type="text" id="tag">
		<script>
		$(function() {
			$("#tag").autocomplete({
				source: "${pageContext.request.contextPath}/domain/rest/tag/autocomplete",
				select: function(event, ui) {
					document.location.href = "${pageContext.request.contextPath}/domain/tag/show/" + ui.item.id;
				},
				focus: function(event, ui) {
					$("#show-tag").load("${pageContext.request.contextPath}/domain/tag/show/" + ui.item.id + ".html table.show");
				}
			});
		});
		</script>
	</div>
	<div id="show-tag" class="span-18 last"></div>
	
	<hr/>

	<form action="${pageContext.request.contextPath}/domain/tag/list">
		<input type="text" name="sp.searchPattern"/>
	</form>
	<div id="result"></div>
</body>
