/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/formatter/Formatter.e.vm.java
 */
package fr.cora.mesindicateurssi.formatter;

import static org.apache.commons.lang.StringUtils.isBlank;

import java.text.ParseException;
import java.util.Locale;

import fr.cora.mesindicateurssi.domain.Indicator;
import fr.cora.mesindicateurssi.repository.IndicatorRepository;
import fr.cora.mesindicateurssi.formatter.support.DiscoverableFormatter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * {@link Formatter} for {@link Indicator} that is picked by automatically by {@link CustomFormattingConversionServiceFactory}
 *
 * @see Formatter
 * @see CustomFormattingConversionServiceFactory
 */
@Component
public class IndicatorFormatter implements DiscoverableFormatter<Indicator> {

    @Autowired
    private IndicatorRepository indicatorRepository;

    @Override
    public Class<Indicator> getTarget() {
        return Indicator.class;
    }

    @Override
    public String print(Indicator indicator, Locale locale) {
        if (indicator == null) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        // make a nice display string here...

        if (indicator.getName() != null) {
            sb.append(indicator.getName()).append(" ");
        }

        if (indicator.getDescription() != null) {
            sb.append(indicator.getDescription()).append(" ");
        }

        if (sb.length() > 0) {
            return sb.toString();
        } else if (indicator.isNew()) {
            return indicator.getId().toString();
        } else {
            return indicator.toString();
        }
    }

    @Override
    public Indicator parse(String text, Locale locale) throws ParseException {
        if (isBlank(text)) {
            return new Indicator();
        }
        Indicator indicator = indicatorRepository.findOne(new Integer(text));
        return indicator != null ? indicator : new Indicator();
    }
}
