/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/formatter/Formatter.e.vm.java
 */
package fr.cora.mesindicateurssi.formatter;

import static org.apache.commons.lang.StringUtils.isBlank;

import java.text.ParseException;
import java.util.Locale;

import fr.cora.mesindicateurssi.domain.Tag;
import fr.cora.mesindicateurssi.repository.TagRepository;
import fr.cora.mesindicateurssi.formatter.support.DiscoverableFormatter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * {@link Formatter} for {@link Tag} that is picked by automatically by {@link CustomFormattingConversionServiceFactory}
 *
 * @see Formatter
 * @see CustomFormattingConversionServiceFactory
 */
@Component
public class TagFormatter implements DiscoverableFormatter<Tag> {

    @Autowired
    private TagRepository tagRepository;

    @Override
    public Class<Tag> getTarget() {
        return Tag.class;
    }

    @Override
    public String print(Tag tag, Locale locale) {
        if (tag == null) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        // make a nice display string here...

        if (tag.getName() != null) {
            sb.append(tag.getName()).append(" ");
        }

        if (sb.length() > 0) {
            return sb.toString();
        } else if (tag.isNew()) {
            return tag.getId().toString();
        } else {
            return tag.toString();
        }
    }

    @Override
    public Tag parse(String text, Locale locale) throws ParseException {
        if (isBlank(text)) {
            return new Tag();
        }
        Tag tag = tagRepository.findOne(new Integer(text));
        return tag != null ? tag : new Tag();
    }
}
