/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-sd:src/test/java/repository/ModelGenerator.e.vm.java
 */
package fr.cora.mesindicateurssi.repository;

import org.springframework.stereotype.Service;
import fr.cora.mesindicateurssi.domain.Category;
import fr.cora.mesindicateurssi.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Service
public class CategoryGenerator {

    /**
     * Returns a new Category instance filled with random values.
     */
    public Category getCategory() {
        Category category = new Category();

        // simple attributes follows
        category.setName("aa");
        return category;
    }

}