/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-sd:src/test/java/repository/RepositoryWithRealSessionTest.e.vm.java
 */
package fr.cora.mesindicateurssi.repository;

import static org.fest.assertions.Assertions.assertThat;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.google.common.collect.Sets;

import fr.cora.mesindicateurssi.domain.Indicator;
import fr.cora.mesindicateurssi.repository.IndicatorGenerator;
import fr.cora.mesindicateurssi.repository.IndicatorRepository;

/**
 * Integration test on {@link IndicatorRepository}
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class IndicatorRepositoryWithRealSessionTest {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(IndicatorRepositoryWithRealSessionTest.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Autowired
    private IndicatorRepository indicatorRepository;

    @Autowired
    private IndicatorGenerator indicatorGenerator;

    @Test
    public void identityShouldBePreserved() {
        Indicator indicator = indicatorGenerator.getIndicator();

        // add it to a Set before saving (force equals/hashcode)
        Sets.newHashSet(indicator);

        indicatorRepository.save(indicator);
        entityManager.flush();

        // reload it from cache and check equality
        Integer id = indicator.getId();
        assertThat(indicator).isEqualTo(indicatorRepository.findOne(id));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(indicator.getId()).isEqualTo(indicatorRepository.findOne(id).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(indicator).isNotEqualTo(indicatorRepository.findOne(id));
    }
}