<%--
 | (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3-sd:src/main/webapp/WEB-INF/views/domain/search.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><fmt:message key="indicator" />: <fmt:message key="crud.functionalities.example" /></title>
</head>
<body>
	<span class="ui-state-highlight button button-search"><fmt:message key="indicator" /></span> 
	<a href="${pageContext.request.contextPath}/domain/indicator/create" class="button button-create"><fmt:message key="crud.functionalities.create" /></a> 
	<a href="${pageContext.request.contextPath}/domain/indicator/showcase" class="button button-create"><fmt:message key="crud.functionalities.showcase" /></a>

	<form:form action="${pageContext.request.contextPath}/domain/indicator/list" modelAttribute="indicatorSearchForm" class="search">
		<table class="show">
			<tbody>
				<tr>
					<th><fmt:message key="indicator_name" /></th>
					<td>
						<form:input path="indicator.name"/>
						<form:errors path="indicator.name" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="indicator_description" /></th>
					<td>
						<form:input path="indicator.description"/>
						<form:errors path="indicator.description" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="indicator_categoryId" /></th>
					<td>
						<form:select id="categoryRestriction" path="categoryNullRestriction.restriction" cssClass="number">
							<form:options />
						</form:select>
						<script>
						$('#categoryRestriction').change(function() {
							if ($('#categoryRestriction option:selected').val() == 'SPECIFIED') { 
								$('#categoryLink,#categoryLabel').removeAttr('disabled');
								$('#categoryLabel').focus();
							} else { 
								$('#categoryLink,#categoryLabel').attr('disabled', 'disabled'); 
							}
						});
						</script>
						<form:hidden id="categoryLink" path="indicator.category" />
						<input type="text" id="categoryLabel"  size="100">
						<script>
						$(function() {
							$('#categoryLabel').autocomplete('destroy');
							$('#categoryLabel').autocomplete({
								source: "${pageContext.request.contextPath}/domain/rest/category/autocomplete",
								select: function(event, ui) {
									$('#categoryLink').val(ui.item.id);
									$('#categoryLabel').val(ui.item.label);
								}
							});
						});
						</script>
						<form:errors path="indicator.categoryId" cssClass="error"/>
					</td>
				</tr>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2">
						<input type="submit" class="button button-search" value="<fmt:message key="crud.search.button" />"/>
					</td>
				</tr>
			</tfoot>
		</table>
	</form:form>
	<div id="result"/>
</body>
