<%--
 | (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3-sd:src/main/webapp/WEB-INF/views/domain/show.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ taglib prefix="spring" uri="http://www.springframework.org/tags"
%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><fmt:message key="indicator" />: <fmt:message key="crud.functionalities.show" /></title>
</head>
<body>
	<a href="${pageContext.request.contextPath}/domain/indicator/search" class="ajaxy button button-search"><fmt:message key="indicator" /></a>
	<span class="ui-state-highlight button button-show"><fmt:message key="crud.show.button" /></span>
	<a href="${pageContext.request.contextPath}/domain/indicator/update/${indicator.id}" class="ajaxy button button-edit"><fmt:message key="crud.edit.button" /></a>
	<a href="${pageContext.request.contextPath}/domain/indicator/delete/${indicator.id}" class="modal button button-delete"><fmt:message key="crud.delete.button" /></a>

	<table class="show">
		<tbody>
			<tr>
				<th><fmt:message key="indicator_name" /></th>
				<td><spring:eval expression="indicator.name"/></td>
			</tr>
			<tr>
				<th><fmt:message key="indicator_description" /></th>
				<td><spring:eval expression="indicator.description"/></td>
			</tr>
			<tr>
				<th><fmt:message key="indicator_categoryId" /></th>
				<td>
					<spring:eval expression="indicator.category" />
					<a href="${pageContext.request.contextPath}/domain/category/show/${indicator.category.id}" class="button button-show miniature"><fmt:message key="crud.show.button" /></a>
				</td>
			</tr>
			<tr>
				<th><fmt:message key="tag" /></th>
				<td>
					<ul class="inline">
						<c:forEach items="${indicator.tags}" var="tag" varStatus="status">
							<li>
								<spring:eval expression="tag" /><a href="${pageContext.request.contextPath}/domain/tag/show/${tag.id}" class="button button-show miniature"><fmt:message key="crud.show.button" /></a>
							</li>
						</c:forEach>
					</ul>
				</td>
			</tr>
		</tbody>
	</table>
</body>