<%--
 | (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3-sd:src/main/webapp/WEB-INF/views/domain/update.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ taglib prefix="spring" uri="http://www.springframework.org/tags"
%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><fmt:message key="indicator" />: <fmt:message key="crud.functionalities.update" /></title>
</head>
<body>
	<a href="${pageContext.request.contextPath}/domain/indicator/search" class="ajaxy button button-search"><fmt:message key="indicator" /></a>
	<a href="${pageContext.request.contextPath}/domain/indicator/show/${indicator.id}" class="ajaxy button button-show"><fmt:message key="crud.show.button" /></a>
	<span class="ui-state-highlight button button-edit"><fmt:message key="crud.edit.button" /></span>
	<a href="${pageContext.request.contextPath}/domain/indicator/delete/${indicator.id}" class="modal button button-delete"><fmt:message key="crud.delete.button" /></a>

	<form:form action="${pageContext.request.contextPath}/domain/indicator/update/${indicator.id}" modelAttribute="indicator" method="POST">
		<form:errors cssClass="error"/>
		<form:hidden path="id"/>
		<table class="edit">
			<tbody>
				<tr>
					<th><fmt:message key="indicator_name" /></th>
					<td>
						<form:input path="name" cssClass="{minlength: 2}" maxlength="128" size="100"/>
						<form:errors path="name" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="indicator_description" /></th>
					<td>
						<form:input path="description" cssClass="{maxlength: 255}" maxlength="255" size="100"/>
						<form:errors path="description" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="indicator_categoryId" /> <em>*</em></th>
					<td>
						<input type="hidden" id="categoryLink" name="category" value="<spring:eval expression="indicator.categoryId" javaScriptEscape="true"/>" />
						<input type="text" id="categoryLabel" value="<spring:eval expression="indicator.category" javaScriptEscape="true"/>" size="100">
						<script>
						$(function() {
							$("#categoryLabel").autocomplete('destroy');
							$("#categoryLabel").autocomplete({
								source: "${pageContext.request.contextPath}/domain/rest/category/autocomplete",
								select: function(event, ui) {
									$("#categoryLink").val(ui.item.id);
									$("#categoryLabel").val(ui.item.label);
								}
							});
						});
						</script>
 						<form:errors path="category" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="tag" /></th>
					<td>
						<form:select path="tags" multiple="true" items="${tags}" itemValue="id"/>
						<form:errors cssClass="error" path="tags"/>
					</td>
				</tr>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2">
						<input type="submit" class="button button-save" value="<fmt:message key="crud.save.button" />" />
					</td>
				</tr>
			</tfoot>
		</table>
	</form:form>
</body>
